// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Sr2vKkaW_q1nbaJwGodklCfq-zB-Plw',
    appId: '1:1059076579006:android:6cb6eec99a66e54c5288ef',
    messagingSenderId: '1059076579006',
    projectId: 'shopping-list-93ccd',
    databaseURL: 'https://shopping-list-93ccd-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-93ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnW4kq-T4gzv_N6Zn59VyG6K_WeHozV0',
    appId: '1:1059076579006:ios:585263b06f4b970d5288ef',
    messagingSenderId: '1059076579006',
    projectId: 'shopping-list-93ccd',
    databaseURL: 'https://shopping-list-93ccd-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-93ccd.appspot.com',
    iosClientId: '1059076579006-png1v9s701ce8n5tc4j8burle58o2vnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
